services:
  hsa:
    container_name: hsa
    build:
      target: builder
    stop_signal: SIGINT
    ports:
      - "9000:9000"
    environment:
      - FLASK_SERVER_PORT=9000
    volumes:
      - ./:/src
    networks:
      - backend

  nginx:
    build:
      context: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
    depends_on:
      - hsa
    networks:
      - backend

#  hping:
#    build: ./hping3
#    depends_on:
#      - nginx
#    networks:
#      - backend

networks:
  backend:
    driver: bridge
