services:
  hsa:
    container_name: hsa
    build:
      target: builder
    stop_signal: SIGINT
    ports:
      - "9000:9000"
    environment:
      - FLASK_SERVER_PORT=9000
    volumes:
      - ./:/src
    networks:
      - backend

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - hsa
    networks:
      - backend

  hping:
    build: ./hping3
    depends_on:
      - nginx
    networks:
      - backend

networks:
  backend:
    driver: bridge
